spring:
  data:
    mongodb:
      #host: 129.211.32.3
      #port: 27017
      #username: orange
      #password: 123456
      #authenticationDatabase: orangeStore
      uri: mongodb://admin:123456@129.211.32.3:27017/?authSource=admin
      database: orangeStore
  port: 8081